### ISSUE TITLE
Feature Request: Also detect esbuild Re-exports

### ISSUE THREAD

**Issue by hyrious** [nodejs/cjs-module-lexer#73]
```js
// pattern:
__reExport(foo_exports, require("x"), module.exports);
__reExport(bar_exports, require("y"));
```

[REPL](https://hyrious.me/esbuild-repl/?version=0.15.5&mode=build&modules=%5B%5B%22foo.js%22%2C%22export+*+from+%5C%22x%5C%22%5Cnexport+*+from+%5C%22.%2Fbar%5C%22%22%2C1%5D%2C%5B%22bar.js%22%2C%22export+*+from+%5C%22y%5C%22%22%2C0%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22platform%22%3A%22node%22%7D)

Consideration: when minified, should this code be detected?:

```js
o(e,require("x"),module.exports);
o(f,require("y"));
```

Consideration2: since esbuild has not been 1.0, this pattern may still change in the future, so you may not in a hurry to implement that.

Related issue: https://github.com/evanw/esbuild/issues/2486

**Comment by evanw** [comment]
FWIW I don't think this is a good idea. This would likely be brittle at least due to how esbuild renames identifiers, so checking for `__reExport` wouldn't work in 100% of cases. It wouldn't work for minified code but also the identifier might be `_reExport2`, etc. This should probably be fixed on esbuild's end instead: https://github.com/evanw/esbuild/issues/2486#issuecomment-1222680909
